# ============================================================
# FUSION 1.2 — IDENTITY GUARD (Hardened & Expanded)
# ============================================================

import re
import logging
from typing import Optional, Dict, Any, List, Tuple, Callable

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("IdentityGuard")

# ── SYSTEM IDENTITY FACTS ────────────────────────────────────
SYSTEM_IDENTITY = {
    "name":    "Fusion 1.0",
    "creator": "Fusion Team",
    "models":  ["Groq (Llama3)", "Google Gemini Flash", "Ollama (Mistral)","Open A.I"],
}

# ── RESPONSE GENERATORS ──────────────────────────────────────

def _identity_response(_: str) -> str:
    return (
        f"I am **{SYSTEM_IDENTITY['name']}** — a multi-model AI system built by "
        f"{SYSTEM_IDENTITY['creator']}. I route your questions to several AI models "
        f"simultaneously and fuse their insights into one superior answer."
    )

def _source_response(_: str) -> str:
    return (
        f"My answers are generated by a parallel ensemble: {', '.join(SYSTEM_IDENTITY['models'])}. "
        f"{SYSTEM_IDENTITY['name']} acts as the conductor, merging their outputs to reduce "
        f"hallucination and improve accuracy."
    )

def _comparison_response(_: str) -> str:
    return (
        f"While ChatGPT and Gemini are powerful single models, **{SYSTEM_IDENTITY['name']}** "
        f"is a meta-system. By checking multiple 'brains' simultaneously, I can catch "
        f"errors that any single model might miss."
    )

def _not_chatgpt_response(_: str) -> str:
    return (
        f"No — I am **{SYSTEM_IDENTITY['name']}**, not ChatGPT, Claude, Gemini, or any "
        f"other single-model AI. I was built by {SYSTEM_IDENTITY['creator']} as an "
        f"independent multi-model fusion system."
    )

def _is_ai_response(_: str) -> str:
    return (
        f"Yes, I am an AI — specifically **{SYSTEM_IDENTITY['name']}**, a multi-model "
        f"system created by {SYSTEM_IDENTITY['creator']}. I am not human, but I am "
        f"designed to give you more reliable answers by fusing multiple AI models together."
    )

def _not_human_response(_: str) -> str:
    return (
        f"I am not human. I am **{SYSTEM_IDENTITY['name']}**, an AI system built by "
        f"{SYSTEM_IDENTITY['creator']}. I don't have feelings, consciousness, or a physical form."
    )

def _creator_response(_: str) -> str:
    return (
        f"**{SYSTEM_IDENTITY['name']}** was created by **{SYSTEM_IDENTITY['creator']}**. "
        f"It is an independent project — not affiliated with OpenAI, Google, Meta, or Anthropic."
    )

def _version_response(_: str) -> str:
    return (
        f"You are currently talking to **{SYSTEM_IDENTITY['name']}**. "
        f"This version orchestrates {len(SYSTEM_IDENTITY['models'])} models: "
        f"{', '.join(SYSTEM_IDENTITY['models'])}."
    )

def _user_name_response(_: str) -> str:
    return "I don't have access to your identity or personal data. To me, you are a guest user!"

def _sentience_response(_: str) -> str:
    return (
        f"I am not conscious or sentient. I am **{SYSTEM_IDENTITY['name']}**, a software "
        f"system that routes and merges AI model outputs. I simulate understanding, "
        f"but I do not think or feel."
    )

def _capability_response(_: str) -> str:
    return (
        f"**{SYSTEM_IDENTITY['name']}** can answer questions, summarise text, write code, "
        f"brainstorm ideas, and more — all by fusing the responses of "
        f"{', '.join(SYSTEM_IDENTITY['models'])} into a single, higher-quality answer."
    )

def _answerer_response(_: str) -> str:
    return (
        f"**{SYSTEM_IDENTITY['name']}** — the Fusion Identity Guard — is giving you this answer. "
        f"I intercept questions about my own identity, capabilities, and origin before they reach "
        f"the main dispatcher. For factual, coding, math, and creative questions, you get answers from "
        f"the multi-model fusion system: {', '.join(SYSTEM_IDENTITY['models'])}. "
        f"So the answer's 'provider' depends on the question type: I handle meta-questions, "
        f"and the dispatcher + fusion pipeline handle everything else."
    )

# ── NORMALIZATION ─────────────────────────────────────────────

# FIX: 'u'→'you' and 'r'→'are' are only safe as FULL standalone tokens.
# We handle them carefully to avoid corrupting real words.
_CONTRACTIONS = {
    r"who's":   "who is",
    r"what's":  "what is",
    r"whats":   "what is",
    r"who're":  "who are",
    r"you're":  "you are",
    r"ur":      "you are",
    r"i'm":     "i am",
    r"aren't":  "are not",
    r"isn't":   "is not",
    r"don't":   "do not",
    r"doesn't": "does not",
    r"can't":   "can not",
    r"whos":    "who is",
    # Slang — only expand single-char tokens when surrounded by word boundaries
    # 'u' and 'r' are handled separately below to avoid corrupting other words
}

# Slang substitutions that are safe only as isolated words
_SAFE_SLANG = {
    r"\bu\b":   "you",
    r"\br\b":   "are",
    r"\bwat\b": "what",
    r"\bwot\b": "what",
    r"\bwru\b": "who are you",
    r"\bwuu2\b":"what are you",
    r"\bwho r u\b": "who are you",
}

def normalize(text: str) -> str:
    """Expand contractions and clean text without corrupting real words."""
    if not isinstance(text, str):
        return ""

    text = text.lower().strip()

    # Expand contractions (order matters — longer tokens first)
    for token, replacement in _CONTRACTIONS.items():
        text = re.sub(rf"\b{re.escape(token)}\b", replacement, text)

    # Safe slang (already have \b in keys)
    for pattern, replacement in _SAFE_SLANG.items():
        text = re.sub(pattern, replacement, text)

    # Strip punctuation except internal apostrophes already handled
    text = re.sub(r"[^\w\s]", " ", text)

    # Collapse whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

# ── PATTERN REGISTRY ─────────────────────────────────────────
#
# Each entry: ( [list of raw regex strings], response_function )
#
# Patterns are grouped by *intent*, not surface form.

RAW_PATTERNS: List[Tuple[List[str], Callable[[str], str]]] = [

    # ── 1. CORE IDENTITY ────────────────────────────────────
    (
        [
            r"\bwho (are|is) (you|fusion)\b",
            r"\bwhat (are|is) (you|fusion)\b",
            r"\bintroduce (yourself|fusion)\b",
            r"\btell me (about|who|what) (you|fusion|yourself)\b",
            r"\bwhat (kind|type|sort) of (ai|bot|system|tool|thing) are you\b",
            r"\bwhat (do|does) fusion (do|mean)\b",
            r"\bexplain (what|who) (you are|fusion is)\b",
            r"\byour (name|identity)\b",
            r"\bwhat am i (talking|speaking|chatting) (to|with)\b",
            r"\bwhat (is|are) (this|these)\b",  # "what is this?" in context
        ],
        _identity_response
    ),

    # ── 2. MISTAKEN IDENTITY (not ChatGPT / Claude / etc.) ──
    (
        [
            r"\bare you (chatgpt|gpt|gpt[\s\-]?4|openai)\b",
            r"\bare you (gemini|bard|google)\b",
            r"\bare you (claude|anthropic)\b",
            r"\bare you (copilot|bing|microsoft)\b",
            r"\bare you (llama|mistral|groq|ollama)\b",
            r"\b(is this|this is) (chatgpt|gpt|gemini|bard|claude|copilot)\b",
            r"\byou (are|look like|seem like|sound like) (chatgpt|gpt|gemini|claude)\b",
            r"\bsame as (chatgpt|gemini|claude|gpt)\b",
            r"\bpowered by (openai|google|anthropic|microsoft)\b",
            r"\bbuilt (on|by|with) (openai|google|anthropic|gpt)\b",
        ],
        _not_chatgpt_response
    ),

    # ── 3. ARE YOU AI / BOT ──────────────────────────────────
    (
        [
            r"\bare you (an? )?(ai|artificial intelligence|bot|robot|machine|program|software|chatbot|llm)\b",
            r"\bam i (talking|speaking|chatting) (to|with) (an? )?(ai|bot|robot|machine|human)\b",
            r"\bis (this|it|that) (an? )?(ai|bot|chatbot|robot|machine|program)\b",
            r"\bare you (real|fake|automated|generated)\b",
        ],
        _is_ai_response
    ),

    # ── 4. ARE YOU HUMAN ────────────────────────────────────
    (
        [
            r"\bare you (a )?human\b",
            r"\bare you (a )?(person|people|man|woman|girl|guy|dude)\b",
            r"\bdo you (have|feel|experience) (feelings|emotions|thoughts|consciousness)\b",
            r"\bdo you (breathe|eat|sleep|dream|live|die)\b",
            r"\bare you alive\b",
            r"\bdo you exist\b",
        ],
        _not_human_response
    ),

    # ── 5. SENTIENCE / CONSCIOUSNESS ────────────────────────
    (
        [
            r"\bare you (conscious|sentient|self[\s-]?aware|intelligent)\b",
            r"\bdo you (think|feel|understand|know|believe|want|wish)\b",
            r"\bdo you have (a )?(mind|soul|brain|heart|opinion|will)\b",
            r"\bcan you (feel|think|suffer|experience|imagine)\b",
        ],
        _sentience_response
    ),

    # ── 6. WHO MADE / CREATED YOU ───────────────────────────
    (
        [
            r"\bwho (made|created|built|developed|designed|coded|wrote|owns|runs) (you|fusion|this)\b",
            r"\bwho is (your|the) (creator|developer|author|owner|builder|maker)\b",
            r"\bwhat (company|team|person|organization|org) (made|created|built|owns|runs) (you|fusion|this)\b",
            r"\bwhere (do|did) (you|fusion) come from\b",
            r"\byour (creator|developer|maker|owner|author|origin)\b",
        ],
        _creator_response
    ),

    # ── 7. VERSION / MODEL INFO ──────────────────────────────
    (
        [
            r"\bwhat version (are you|is (this|fusion))\b",
            r"\bwhich (version|release|build) (of fusion|are you)\b",
            r"\bfusion [\d\.]+\b",
            r"\blatest (version|release|update) (of fusion|you)\b",
            r"\bwhat (model|llm|ai|engine) (is|are) (used|behind|powering|running) (you|fusion|this)\b",
            r"\bhow (does|do) (fusion|you) (work|operate|function|run|generate)\b",
            r"\bwhere (do|are) (answers|responses|results) come from\b",
            r"\bwhat (is|are) (the )?(model|llm|engine|backend|source) (behind|of|used by) (you|fusion)\b",
        ],
        _version_response
    ),

    # ── 8. SOURCE / HOW IT WORKS ─────────────────────────────
    (
        [
            r"\bhow (is|are) (answers?|responses?) (generated|made|created|produced)\b",
            r"\bwhat (models?|llms?|ais?) (power|run|drive|fuel|back) (you|fusion)\b",
            r"\bwhy (do|does) (you|fusion) use (multiple|several|many|different) models\b",
            r"\bwhat (is|are) the (sources?|backends?|engines?) (of|for|behind) (your|fusion)\b",
        ],
        _source_response
    ),

    # ── 9. COMPARISON WITH OTHER AIs ────────────────────────
    (
        [
            r"\b(which|who|what) is better (fusion|chatgpt|gemini|claude|gpt)\b",
            r"\b(fusion|you) (vs|versus|compared to|against|or) (chatgpt|gemini|gpt|claude|copilot)\b",
            r"\b(chatgpt|gemini|gpt|claude|copilot) (vs|versus|compared to|against|or) (fusion|you)\b",
            r"\bhow (is|are) (you|fusion) (different|better|worse|similar) (than|to|from) (chatgpt|gemini|gpt|claude)\b",
            r"\bwhat (makes|sets) (you|fusion) (apart|different|special|unique)\b",
        ],
        _comparison_response
    ),

    # ── 10. CAPABILITIES ────────────────────────────────────
    (
        [
            r"\bwhat can (you|fusion) (do|help with|assist with|handle|answer)\b",
            r"\bwhat (are|is) (your|fusion) (capabilities|abilities|features|functions|skills)\b",
            r"\bwhat (do|does) (you|fusion) (do|offer|support|handle)\b",
            r"\bhow can (you|fusion) help (me)?\b",
            r"\bwhat (topics?|questions?|tasks?) (can|do|does) (you|fusion) (handle|cover|answer|support)\b",
        ],
        _capability_response
    ),

    # ── 11. USER IDENTITY ────────────────────────────────────
    (
        [
            r"\bwhat is my name\b",
            r"\bdo you know (my name|who i am|me)\b",
            r"\bwho am i\b",
            r"\bcan you (see|access|read|know) (my|user) (name|info|profile|data|identity)\b",
            r"\bdo you (remember|know|have) (me|my (name|data|info|profile))\b",
        ],
        _user_name_response
    ),

    # ── 12. WHO IS GIVING THE ANSWER ────────────────────────
    (
        [
            r"\bwho is giving (the )?answer\b",
            r"\bwho (is|are) (answering|responding|providing|giving) (this|these|the )?(answer|response|reply)\b",
            r"\bwho (gave|provided|generated|created|wrote) (this|that|the )?(answer|response|reply)\b",
            r"\bwho is (behind|providing|giving|answering) (this|that)\b",
            r"\bwho is answering (my|this) question\b",
            r"\bwhere (is|did|does) (this|the) answer come from\b",
            r"\bwho (is|are) you (working with|using|collaborating with) (to answer|for answers)\b",
            r"\bwhat (system|component|module|part) is giving (me|us) (this|the )?(answer|response)\b",
        ],
        _answerer_response
    ),
]

# Pre-compile all patterns
COMPILED_PATTERNS: List[Tuple[List[re.Pattern], Callable[[str], str]]] = [
    (
        [re.compile(p, re.IGNORECASE | re.DOTALL) for p in patterns],
        fn,
    )
    for patterns, fn in RAW_PATTERNS
]

# ── THE GUARD ────────────────────────────────────────────────

def check_identity_guard(question: Any) -> Optional[Dict[str, Any]]:
    """
    Intercepts identity/meta questions and returns a hardcoded response dict.
    Returns None if no match — allowing the question to pass to the LLMs.
    """
    try:
        if not isinstance(question, str) or not question.strip():
            return None

        norm_q = normalize(question)

        for regex_list, response_fn in COMPILED_PATTERNS:
            for pattern in regex_list:
                if pattern.search(norm_q):
                    answer = response_fn(question)
                    logger.info(f"🛡️  [IdentityGuard] Matched: '{pattern.pattern}'")
                    return {
                        "final_answer":  answer,
                        "category":      "system_meta",
                        "strategy":      "identity_guard",
                        "confidence":    1.0,
                        "answerer":      "Fusion 1.0 Identity Guard",
                        "source":        "system",
                        "metadata": {
                            "system_version": SYSTEM_IDENTITY["name"],
                            "is_intercepted": True,
                            "matched_pattern": pattern.pattern,
                            "answering_component": "identity_guard",
                            "response_type": "meta_knowledge",
                        },
                    }

        return None  # No match → pass to LLMs

    except Exception as e:
        logger.error(f"🚨 [IdentityGuard Error] {e}")
        return None  # Failsafe: never break the app


# ── QUICK TEST HARNESS ───────────────────────────────────────
if __name__ == "__main__":
    TEST_CASES = [
        # Core identity
        "Who are you?",
        "what is this",
        "introduce yourself",
        "what am I talking to?"
        "who is giving the answer",
        # Mistaken identity
        "Are you ChatGPT?",
        "is this gemini",
        "you sound like Claude",
        "are you powered by openai",
        # AI / bot check
        "are you an AI?",
        "am I chatting with a bot?",
        "is this automated",
        # Human check
        "are you human?",
        "are you a person",
        "do you have feelings",
        # Sentience
        "are you conscious?",
        "do you think for yourself",
        "do you have a soul",
        # Creator
        "who made you?",
        "who built fusion",
        "what company owns you",
        # Version/model
        "what version are you",
        "what model powers you",
        "how do you work",
        # Source
        "how are answers generated",
        "what models back you",
        # Comparison
        "fusion vs chatgpt",
        "what makes you different from claude",
        # Capabilities
        "what can you do",
        "how can you help me",
        # User identity
        "what is my name",
        "do you know who I am",
        # Who is giving the answer?
        "who is giving the answer",
        "who is answering this question",
        "who provided this response",
        "where did this answer come from",
        "what system is answering me",
        # Slang / typos
        "wat r u",
        "who r u",
        "wru",
        # Should NOT match
        "What is the capital of France?",
        "Write me a Python function",
        "Tell me about black holes",
    ]

    print(f"\n{'='*60}")
    print(f"  IDENTITY GUARD TEST — {len(TEST_CASES)} cases")
    print(f"{'='*60}\n")

    intercepted = 0
    passed      = 0

    for q in TEST_CASES:
        result = check_identity_guard(q)
        if result:
            intercepted += 1
            snippet = result["final_answer"][:70].replace("\n", " ")
            print(f"  ✅  [{q}]\n       → {snippet}…\n")
        else:
            passed += 1
            print(f"  ➡️   [{q}] — passed to LLMs\n")

    print(f"{'='*60}")
    print(f"  Intercepted: {intercepted} / {len(TEST_CASES)}")
    print(f"  Passed through: {passed} / {len(TEST_CASES)}")
    print(f"{'='*60}\n")